title = "gitleaks config"

[allowlist]
description = "Ignore generated and third-party directories"
paths = [
  '''^node_modules/''',
  '''^dist/''',
  '''^coverage/''',
  '''^\.idea/''',
  '''^\.crush/''',
  '''^\.env\.example$'''
]

# Optionally allow common placeholder patterns only within example files
# (kept minimal to avoid masking real leaks)
# regexes = [
#   '''(?i)PLACEHOLDER''',
#   '''(?i)DUMMY''',
#   '''(?i)EXAMPLE''',
# ]
