name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bun checks (lint, typecheck, build, tests, format)
        uses: docker://oven/bun:1.2.2-debian
        with:
          entrypoint: sh
          args: -lc "set -eu; apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/* && bun --version && bun install --frozen-lockfile || bun install && bun run lint && bun run typecheck && bun run build:cli && bun run build:plugin && bun run test:coverage && bun run format:check"

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage

      # Format check already covered in Bun container step above
